In [3]:
import pandas as pd

orders_df = pd.read_csv("../Python_Analysis/data/orders.csv")

orders_df.head()

,order_id,order_date,customer_id,store_name,region,total_sales
0,1,2023-06-05,1,NY Downtown,North America,1500.0
1,2,2023-06-06,2,London Central,Europe,800.0
2,3,2023-06-10,3,Dubai Mall,Middle East,300.0
3,4,2023-06-12,4,Shanghai Plaza,Asia,350.0
4,6,2023-06-20,6,Berlin Hub,Europe,180.0

In [4]:
#Monthly Revenue Trend
orders_df['order_date'] = pd.to_datetime(orders_df['order_date'])

monthly_revenue = (
    orders_df
    .groupby(orders_df['order_date'].dt.to_period('M'))
    ['total_sales']
    .sum()
    .reset_index()
)

monthly_revenue

  order_date  total_sales
0    2023-06       4330.0

In [5]:
#Top Customers by Revenue

top_customers = (
    orders_df
    .groupby('store_name')['total_sales']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

top_customers

       store_name  total_sales
0     NY Downtown       2700.0
1  London Central        800.0
2  Shanghai Plaza        350.0
3      Dubai Mall        300.0
4      Berlin Hub        180.0

In [6]:
#Regional performance
region_revenue = (
    orders_df
    .groupby('region')['total_sales']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

region_revenue

          region  total_sales
0  North America       2700.0
1         Europe        980.0
2           Asia        350.0
3    Middle East        300.0

In [7]:
#Prepare Monthly Revenue Properly
orders_df['order_date'] = pd.to_datetime(orders_df['order_date'])

monthly_revenue = (
    orders_df
    .groupby(orders_df['order_date'].dt.to_period('M'))
    ['total_sales']
    .sum()
    .reset_index()
)

monthly_revenue['order_month'] = monthly_revenue['order_date'].astype(str)
monthly_revenue

  order_date  total_sales order_month
0    2023-06       4330.0     2023-06

In [8]:
#Month-over-Month (MoM) Growth
monthly_revenue = monthly_revenue.sort_values('order_month')

monthly_revenue['previous_month_sales'] = (
    monthly_revenue['total_sales'].shift(1)
)

monthly_revenue['mom_growth_pct'] = (
    (monthly_revenue['total_sales'] - monthly_revenue['previous_month_sales'])
    / monthly_revenue['previous_month_sales']
) * 100

monthly_revenue

  order_date  total_sales order_month  previous_month_sales  mom_growth_pct
0    2023-06       4330.0     2023-06                   NaN             NaN

In [9]:
#Regional Performance Analysis
regional_sales = (
    orders_df
    .groupby('region')['total_sales']
    .sum()
    .reset_index()
    .sort_values('total_sales', ascending=False)
)

regional_sales

          region  total_sales
3  North America       2700.0
1         Europe        980.0
0           Asia        350.0
2    Middle East        300.0

In [10]:
#Store Performance (Top & Bottom Stores)
store_performance = (
    orders_df
    .groupby('store_name')['total_sales']
    .sum()
    .reset_index()
    .sort_values('total_sales', ascending=False)
)

store_performance.head(5)   # Top stores
store_performance.tail(5)   # Bottom stores

       store_name  total_sales
3     NY Downtown       2700.0
2  London Central        800.0
4  Shanghai Plaza        350.0
1      Dubai Mall        300.0
0      Berlin Hub        180.0

In [11]:
import os
os.makedirs("../data/processed", exist_ok=True)

monthly_revenue.to_csv(
    "../data/processed/monthly_revenue.csv", index=False
)

regional_sales.to_csv(
    "../data/processed/regional_sales.csv", index=False
)

store_performance.to_csv(
    "../data/processed/store_performance.csv", index=False
)

In [12]:
orders_df.columns

Index(['order_id', 'order_date', 'customer_id', 'store_name', 'region',
       'total_sales'],
      dtype='object')

In [13]:
orders_df.head()

,order_id,order_date,customer_id,store_name,region,total_sales
0,1,2023-06-05,1,NY Downtown,North America,1500.0
1,2,2023-06-06,2,London Central,Europe,800.0
2,3,2023-06-10,3,Dubai Mall,Middle East,300.0
3,4,2023-06-12,4,Shanghai Plaza,Asia,350.0
4,6,2023-06-20,6,Berlin Hub,Europe,180.0